### ISSUE TITLE
GET requests or bad payloads make the SDK panic

### ISSUE THREAD

**Issue by antoineco** [cloudevents/sdk-go#477]
The receiver panics when receiving a GET request of empty payload.

Given this client
```go
func main() {
    cli, _ := cloudevents.NewDefaultClient()
    cli.StartReceiver(ctx, func(cloudevents.Event) {})
}
```

just `curl localhost:8080`.

<details><summary>📄 error trace</summary>

```
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7b2946]

goroutine 19 [running]:
github.com/cloudevents/sdk-go/v2/protocol/http.(*Message).Finish(0x0, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.0.0-!r!c1/protocol/http/message.go:151 +0x26
github.com/cloudevents/sdk-go/v2/client.(*receiveInvoker).Invoke.func1(0xd91c20, 0x0, 0xc00006de78)
        /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.0.0-!r!c1/client/invoker.go:41 +0x47
panic(0xba6860, 0x128d010)
        /usr/local/go/src/runtime/panic.go:969 +0x166
github.com/cloudevents/sdk-go/v2/protocol/http.(*Message).ReadEncoding(0x0, 0xc000020000)
        /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.0.0-!r!c1/protocol/http/message.go:81 +0x5
github.com/cloudevents/sdk-go/v2/binding.ToEvent(0xd91c60, 0xc0000ae000, 0x7fce984681a0, 0x0, 0x0, 0x0, 0x0, 0xc00006ddbc, 0x2, 0x2)
        /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.0.0-!r!c1/binding/to_event.go:28 +0x52
github.com/cloudevents/sdk-go/v2/client.(*receiveInvoker).Invoke(0xc00009e560, 0xd91c60, 0xc0000ae000, 0xd91c20, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.0.0-!r!c1/client/invoker.go:46 +0xfc
github.com/cloudevents/sdk-go/v2/client.(*ceClient).StartReceiver(0xc0000ce0a0, 0xd91c60, 0xc0000ae000, 0xb69e00, 0xcc3008, 0x0, 0x0)
        /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.0.0-!r!c1/client/client.go:218 +0x287
github.com/cloudevents/sdk-go/v2/client.(*obsClient).StartReceiver(0xc00009e540, 0xd91c60, 0xc0000ae000, 0xb69e00, 0xcc3008, 0x0, 0x0)
        /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.0.0-!r!c1/client/client_observed.go:93 +0xac
main.(*handler).Start.func1(0xc0000dc0c0, 0xc0000b03d0, 0xd91c60, 0xc0000ae000)
        /go/src/github.com/triggermesh/myproject/cmd/mycmdtarget/main.go:85 +0x63
created by main.(*handler).Start
        /go/src/github.com/triggermesh/myproject/cmd/mycmdtarget/main.go:84 +0x7a
exit status 2
```

</details>

The culprit is here:

https://github.com/cloudevents/sdk-go/blob/0fc16e13d87f0f2b1c99ec41183e35c0e68b6b5c/v2/binding/to_event.go#L23-L26

This comparison is `false` even when the request contains no payload.

---

edit: I observe the same result by sending valid payloads with a "bad" or missing `Content-Type` header:

```
$ curl -XPOST -H "Content-Type: application/json" localhost:8080/ -d'{
    "specversion" : "1.0",
    "type" : "com.example.someevent",
    "source" : "/mycontext",
    "id" : "A234-1234-1234",
    "time" : "2018-04-05T17:31:00Z",
    "comexampleextension1" : "value",
    "comexampleothervalue" : 5,
    "datacontenttype" : "text/xml",
    "data" : "<much wow=\"xml\"/>"
}'

// missing "+json" in the header -> boom
```

**Comment by antoineco** [comment]
@slinkydeveloper in case you haven't figured out what happened yet, the issue is described here: https://dev.to/pauljlucas/go-tcha-when-nil--nil-hic (thanks @odacremolbap for pointing that out).

> whenever you assign to an `interface` (either explicitly via assignment or implicitly via `return` value), it takes on both the value and the concrete type. Once it takes on a concrete type, it will never compare equal to (the typeless) `nil`.

**Comment by antoineco** [comment]
Same result when the `Content-Type` header is not `application/cloudevents`. Editing the issue description.

**Comment by antoineco** [comment]
@slinkydeveloper I tackled this because it's causing issues with a project I'm currently working in.
