### ISSUE TITLE
Panic error in `v2.0.0-preview8`

### ISSUE THREAD

**Issue by jonatasbaldin** [cloudevents/sdk-go#485]
The `v2.0.0-preview8` is getting a panic error when receiving an event. I tested with the [http receiver example](https://github.com/cloudevents/sdk-go/blob/master/v2/cmd/samples/http/receiver/main.go).

Golang version: `go version go1.14.2 darwin/amd64`

Here's the error:
```
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x13a9bb6]

goroutine 1 [running]:
github.com/cloudevents/sdk-go/v2/protocol/http.(*Message).Finish(0x0, 0x0, 0x0, 0xc00025f9a8, 0x1055a79)
        /Users/jonatasbaldin/go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.0.0-preview8/protocol/http/message.go:123 +0x26
github.com/cloudevents/sdk-go/v2/client.(*receiveInvoker).Invoke.func1(0x153a7a0, 0x0, 0xc00025fe80)
        /Users/jonatasbaldin/go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.0.0-preview8/client/invoker.go:41 +0x47
panic(0x141fa80, 0x18156d0)
        /usr/local/Cellar/go/1.14.2/libexec/src/runtime/panic.go:969 +0x166
github.com/cloudevents/sdk-go/v2/protocol/http.(*Message).ReadEncoding(0x0, 0x13c78dd)
        /Users/jonatasbaldin/go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.0.0-preview8/protocol/http/message.go:69 +0x5
github.com/cloudevents/sdk-go/v2/binding.ToEvent(0x153a520, 0xc0000a2000, 0x1f11008, 0x0, 0x0, 0x0, 0x0, 0xc00025fdc4, 0x2, 0x2)
        /Users/jonatasbaldin/go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.0.0-preview8/binding/to_event.go:28 +0x52
github.com/cloudevents/sdk-go/v2/client.(*receiveInvoker).Invoke(0xc0000aea60, 0x153a520, 0xc0000a2000, 0x153a7a0, 0x0, 0x0, 0x0, 0x0)
        /Users/jonatasbaldin/go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.0.0-preview8/client/invoker.go:46 +0xfc
github.com/cloudevents/sdk-go/v2/client.(*ceClient).StartReceiver(0xc0000f9540, 0x153a520, 0xc0000a2000, 0x1404980, 0x14b61f8, 0x0, 0x0)
        /Users/jonatasbaldin/go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.0.0-preview8/client/client.go:218 +0x287
main.main()
        /Users/jonatasbaldin/scratch/cev2/main.go:24 +0x16e
```

Using the latest `v2.0.0-RC2` version, is works like a charm.

**Comment by slinkydeveloper** [comment]
Hi  @jonatasbaldin any particular reason why you need to use preview8? We're not supporting preview releases

**Comment by jonatasbaldin** [comment]
Not at all. Just because the README states the `preview-8` and I think people might try to use that first because it is there. 

What do you think about updating the README with a `go get` command with the recommended version?

**Comment by slinkydeveloper** [comment]
I'll do that, thanks for the suggestion!

**Comment by jonatasbaldin** [comment]
Perfect!
