### ISSUE TITLE
NATS flaky tests

### ISSUE THREAD

**Issue by slinkydeveloper** [cloudevents/sdk-go#630]
```
 === RUN   TestSendStructuredMessagedToStructures/regular_subscriber/Event{"data":"hello","datacontenttype":"text/json","dataschema":"http://example.com/schema","exbinary":"AAECAw==","exbool":true,"exint":42,"exstring":"exstring","extime":"2020-03-21T12:34:56.78Z","exurl":"http://example.com/source","id":"full-event-0","source":"http://example.com/source","specversion":"1.0","subject":"topic","time":"2020-03-21T12:34:56.78Z","type":"com.example.FullEvent"}
coverage: [no statements]
panic: test timed out after 5m0s

goroutine 15 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.14.12/x64/src/testing/testing.go:1514 +0x11c
created by time.goFunc
	/opt/hostedtoolcache/go/1.14.12/x64/src/time/sleep.go:168 +0x52

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0001b7560, 0xbdc7fb, 0x26, 0xbec968, 0x0)
	/opt/hostedtoolcache/go/1.14.12/x64/src/testing/testing.go:1096 +0x570
testing.runTests.func1(0xc0001b7560)
	/opt/hostedtoolcache/go/1.14.12/x64/src/testing/testing.go:1339 +0xa7
testing.tRunner(0xc0001b7560, 0xc0002bfce8)
	/opt/hostedtoolcache/go/1.14.12/x64/src/testing/testing.go:1050 +0x1ec
testing.runTests(0xc00000f6c0, 0x1087850, 0x1, 0x1, 0x0)
	/opt/hostedtoolcache/go/1.14.12/x64/src/testing/testing.go:1337 +0x595
testing.(*M).Run(0xc000156300, 0x0)
	/opt/hostedtoolcache/go/1.14.12/x64/src/testing/testing.go:1252 +0x300
main.main()
	_testmain.go:88 +0x348

goroutine 6 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc00013c280)
	/home/runner/go/pkg/mod/go.opencensus.io@v0.22.3/stats/view/worker.go:154 +0x1d6
created by go.opencensus.io/stats/view.init.0
	/home/runner/go/pkg/mod/go.opencensus.io@v0.22.3/stats/view/worker.go:32 +0x9a

goroutine 7 [chan receive]:
testing.(*T).Run(0xc0001b7680, 0xbd2502, 0x12, 0xc00000f740, 0xc0000285d0)
	/opt/hostedtoolcache/go/1.14.12/x64/src/testing/testing.go:1096 +0x570
github.com/cloudevents/sdk-go/test/integration/nats.TestSendStructuredMessagedToStructures(0xc0001b7680)
	/home/runner/work/sdk-go/sdk-go/test/integration/nats/nats_test.go:48 +0x489
testing.tRunner(0xc0001b7680, 0xbec968)
	/opt/hostedtoolcache/go/1.14.12/x64/src/testing/testing.go:1050 +0x1ec
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.14.12/x64/src/testing/testing.go:1095 +0x538

goroutine 19 [IO wait]:
internal/poll.runtime_pollWait(0x7f8bc7208e08, 0x72, 0xc9a460)
	/opt/hostedtoolcache/go/1.14.12/x64/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc000156498, 0x72, 0x8000, 0x8000, 0xffffffffffffffff)
	/opt/hostedtoolcache/go/1.14.12/x64/src/internal/poll/fd_poll_runtime.go:87 +0xe4
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.14.12/x64/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000156480, 0xc000332000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.14.12/x64/src/internal/poll/fd_unix.go:169 +0x253
net.(*netFD).Read(0xc000156480, 0xc000332000, 0x8000, 0x8000, 0x6, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.14.12/x64/src/net/fd_unix.go:202 +0x66
net.(*conn).Read(0xc0000107a0, 0xc000332000, 0x8000, 0x8000, 0xc00032c000, 0xc000023af8, 0x0)
	/opt/hostedtoolcache/go/1.14.12/x64/src/net/net.go:184 +0xa1
github.com/nats-io/nats%2ego.(*Conn).readLoop(0xc000023600)
	/home/runner/go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/nats.go:2144 +0x18f
created by github.com/nats-io/nats%2ego.(*Conn).processConnectInit
	/home/runner/go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/nats.go:1489 +0x2b6

goroutine 8 [IO wait]:
internal/poll.runtime_pollWait(0x7f8bc7208ee8, 0x72, 0xc9a460)
	/opt/hostedtoolcache/go/1.14.12/x64/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc0000ae118, 0x72, 0x8000, 0x8000, 0xffffffffffffffff)
	/opt/hostedtoolcache/go/1.14.12/x64/src/internal/poll/fd_poll_runtime.go:87 +0xe4
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.14.12/x64/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0000ae100, 0xc0002ea000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.14.12/x64/src/internal/poll/fd_unix.go:169 +0x253
net.(*netFD).Read(0xc0000ae100, 0xc0002ea000, 0x8000, 0x8000, 0x6, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.14.12/x64/src/net/fd_unix.go:202 +0x66
net.(*conn).Read(0xc0000b4020, 0xc0002ea000, 0x8000, 0x8000, 0xc0001ecc00, 0xc0000aa4f8, 0x0)
	/opt/hostedtoolcache/go/1.14.12/x64/src/net/net.go:184 +0xa1
github.com/nats-io/nats%2ego.(*Conn).readLoop(0xc0000aa000)
	/home/runner/go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/nats.go:2144 +0x18f
created by github.com/nats-io/nats%2ego.(*Conn).processConnectInit
	/home/runner/go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/nats.go:1489 +0x2b6

goroutine 9 [chan receive]:
github.com/nats-io/nats%2ego.(*Conn).flusher(0xc0000aa000)
	/home/runner/go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/nats.go:2392 +0x192
created by github.com/nats-io/nats%2ego.(*Conn).processConnectInit
	/home/runner/go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/nats.go:1490 +0x2db

goroutine 10 [sync.Cond.Wait]:
runtime.goparkunlock(...)
	/opt/hostedtoolcache/go/1.14.12/x64/src/runtime/proc.go:310
sync.runtime_notifyListWait(0xc0000b0050, 0xc000000000)
	/opt/hostedtoolcache/go/1.14.12/x64/src/runtime/sema.go:513 +0xf8
sync.(*Cond).Wait(0xc0000b0040)
	/opt/hostedtoolcache/go/1.14.12/x64/src/sync/cond.go:56 +0x8e
github.com/nats-io/nats%2ego.(*asyncCallbacksHandler).asyncCBDispatcher(0xc00009a040)
	/home/runner/go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/nats.go:2067 +0x53
created by github.com/nats-io/nats%2ego.Options.Connect
	/home/runner/go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/nats.go:1074 +0x449

goroutine 11 [chan receive]:
testing.(*T).Run(0xc0001b77a0, 0xc00031e4e0, 0x187, 0xc000080500, 0x0)
	/opt/hostedtoolcache/go/1.14.12/x64/src/testing/testing.go:1096 +0x570
github.com/cloudevents/sdk-go/v2/test.EachEvent(0xc0001b77a0, 0xc0000fa000, 0x4, 0x4, 0xc00009cc00)
	/home/runner/work/sdk-go/sdk-go/v2/test/helpers.go:84 +0x25f
github.com/cloudevents/sdk-go/test/integration/nats.TestSendStructuredMessagedToStructures.func1(0xc0001b77a0)
	/home/runner/work/sdk-go/sdk-go/test/integration/nats/nats_test.go:51 +0x21c
testing.tRunner(0xc0001b77a0, 0xc00000f740)
	/opt/hostedtoolcache/go/1.14.12/x64/src/testing/testing.go:1050 +0x1ec
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.14.12/x64/src/testing/testing.go:1095 +0x538

goroutine 20 [chan receive]:
github.com/nats-io/nats%2ego.(*Conn).flusher(0xc000023600)
	/home/runner/go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/nats.go:2392 +0x192
created by github.com/nats-io/nats%2ego.(*Conn).processConnectInit
	/home/runner/go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/nats.go:1490 +0x2db

goroutine 21 [sync.Cond.Wait]:
runtime.goparkunlock(...)
	/opt/hostedtoolcache/go/1.14.12/x64/src/runtime/proc.go:310
sync.runtime_notifyListWait(0xc0002e4510, 0xc000000000)
	/opt/hostedtoolcache/go/1.14.12/x64/src/runtime/sema.go:513 +0xf8
sync.(*Cond).Wait(0xc0002e4500)
	/opt/hostedtoolcache/go/1.14.12/x64/src/sync/cond.go:56 +0x8e
github.com/nats-io/nats%2ego.(*asyncCallbacksHandler).asyncCBDispatcher(0xc00000f7a0)
	/home/runner/go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/nats.go:2067 +0x53
created by github.com/nats-io/nats%2ego.Options.Connect
	/home/runner/go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/nats.go:1074 +0x449

goroutine 22 [select]:
github.com/cloudevents/sdk-go/protocol/nats/v2.(*Consumer).OpenInbound(0xc0000803c0, 0xca3ba0, 0xc00002c070, 0x0, 0x0)
	/home/runner/work/sdk-go/sdk-go/protocol/nats/v2/receiver.go:103 +0x2cd
github.com/cloudevents/sdk-go/protocol/nats/v2.(*Protocol).OpenInbound(...)
	/home/runner/work/sdk-go/sdk-go/protocol/nats/v2/protocol.go:70
github.com/cloudevents/sdk-go/test/integration/nats.testProtocol.func1(0xca9700, 0xc0001b77a0, 0xc000080370)
	/home/runner/work/sdk-go/sdk-go/test/integration/nats/nats_test.go:97 +0x87
created by github.com/cloudevents/sdk-go/test/integration/nats.testProtocol
	/home/runner/work/sdk-go/sdk-go/test/integration/nats/nats_test.go:96 +0x3ac

goroutine 23 [semacquire]:
sync.runtime_Semacquire(0xc0000a2e98)
	/opt/hostedtoolcache/go/1.14.12/x64/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc0000a2e90)
	/opt/hostedtoolcache/go/1.14.12/x64/src/sync/waitgroup.go:130 +0xd4
github.com/cloudevents/sdk-go/v2/protocol/test.SendReceive(0xc0000e8a20, 0xca3c20, 0xc00009d350, 0xca3ea0, 0xc00009d320, 0xc98d40, 0xc00009a380, 0xc98ce0, 0xc0000803c0, 0xc0000805a0)
	/home/runner/work/sdk-go/sdk-go/v2/protocol/test/test.go:58 +0x1ba
github.com/cloudevents/sdk-go/test/integration/nats.TestSendStructuredMessagedToStructures.func1.1(0xc0000e8a20, 0xcab200, 0xc0000a55f0, 0xc0000a2cd0, 0x7, 0x7, 0x0, 0x0)
	/home/runner/work/sdk-go/sdk-go/test/integration/nats/nats_test.go:56 +0x47e
github.com/cloudevents/sdk-go/v2/test.EachEvent.func1(0xc0000e8a20)
	/home/runner/work/sdk-go/sdk-go/v2/test/helpers.go:84 +0xab
testing.tRunner(0xc0000e8a20, 0xc000080500)
	/opt/hostedtoolcache/go/1.14.12/x64/src/testing/testing.go:1050 +0x1ec
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.14.12/x64/src/testing/testing.go:1095 +0x538

goroutine 24 [select]:
github.com/cloudevents/sdk-go/protocol/nats/v2.(*Receiver).Receive(0xc0000803c0, 0xca3c20, 0xc00009d350, 0x0, 0xc000080500, 0xcab200, 0xc0000a4dd0)
	/home/runner/work/sdk-go/sdk-go/protocol/nats/v2/receiver.go:35 +0x129
github.com/cloudevents/sdk-go/v2/protocol/test.SendReceive.func1(0xc0000a2e90, 0xc98ce0, 0xc0000803c0, 0xca3c20, 0xc00009d350, 0xc0000e8a20, 0xc0000805a0)
	/home/runner/work/sdk-go/sdk-go/v2/protocol/test/test.go:25 +0xae
created by github.com/cloudevents/sdk-go/v2/protocol/test.SendReceive
	/home/runner/work/sdk-go/sdk-go/v2/protocol/test/test.go:23 +0x148

goroutine 26 [sync.Cond.Wait]:
runtime.goparkunlock(...)
	/opt/hostedtoolcache/go/1.14.12/x64/src/runtime/proc.go:310
sync.runtime_notifyListWait(0xc0000b0550, 0xc000000000)
	/opt/hostedtoolcache/go/1.14.12/x64/src/runtime/sema.go:513 +0xf8
sync.(*Cond).Wait(0xc0000b0540)
	/opt/hostedtoolcache/go/1.14.12/x64/src/sync/cond.go:56 +0x8e
github.com/nats-io/nats%2ego.(*Conn).waitForMsgs(0xc000023600, 0xc00033a000)
	/home/runner/go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/nats.go:2178 +0x632
created by github.com/nats-io/nats%2ego.(*Conn).subscribeLocked
	/home/runner/go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/nats.go:3048 +0x822
FAIL	github.com/cloudevents/sdk-go/test/integration/nats	300.048s
FAIL
```

Can you check these out @dan-j @n3wscott ?

**Comment by n3wscott** [comment]
I will have to look later next week.

**Comment by bruth** [comment]
Has this been resolved or is there anything I can help with to resolve this?

**Comment by maxklav** [comment]
Any update on this?
